import type { Metadata } from "next";
import "./globals.css";

// 移除可能导致兼容性问题的 next/font/google 导入
// 暂时使用默认字体，后续可以通过 CSS 自定义字体

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
